permissions:
  contents: write
on:
  push:
    branches: [ master ]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    name: build thesis
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: paper.tex
          extra_fonts: fonts/*
          latexmk_use_xelatex: true
          pre_compile: |
            apk add msttcorefonts-installer fontconfig
            update-ms-fonts
            fc-cache -f
  #     - name: Archive with rar
  #       run: |
  #         sudo apt install rar
  #         rar a paper.rar paper.pdf
  #     - name: Calculate MD5
  #       run: hash=$(md5sum paper.rar | awk '{print $1}') && echo "MD5_HASH=$hash" >> $GITHUB_ENV
  #     - name: Prepare-release
  #       run: |
  #         mv paper.pdf ${{ github.sha }}.pdf
  #         mv paper.rar ${{ env.MD5_HASH }}.rar
  #         echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         name: Build result for ${{ github.sha }}
  #         files: |
  #           ${{ github.sha }}.pdf
  #           ${{ env.MD5_HASH }}.rar
  #         tag_name: ${{ env.SHORT_SHA }}
  fmt:
    runs-on: ubuntu-latest
    name: format thesis and bib
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install latexindent
        run: |
          sudo wget https://github.com/cmhughes/latexindent.pl/releases/download/V3.22.2/latexindent-linux -O /usr/bin/latexindent
          sudo chmod +x /usr/bin/latexindent
      - name: Install bibtex-tidy
        run: npm install -g bibtex-tidy
      - name: Run fomatter
        run: |
           latexindent -w *.tex
           latexindent -w *.cls
           bibtex-tidy ref.bib
      - uses: EndBug/add-and-commit@v9
        with:
          add: |
            '*.tex'
            '*.cls'
            '*.bib'
          default_author: github_actions
          message: 'Autofmt by latexindent/bibtex-tidy'
