permissions:
  contents: write
on:
  push:
    branches: [ master ]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    name: build thesis
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: paper.tex
          extra_fonts: fonts/*
          latexmk_use_xelatex: true
          pre_compile: |
            apk add msttcorefonts-installer fontconfig
            update-ms-fonts
            fc-cache -f
      - name: Pre-release
        run: mv paper.pdf ${{ github.sha }}.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Build result for ${{ github.sha }}
          files: ${{ github.sha }}.pdf
  fmt:
    runs-on: ubuntu-latest
    name: format thesis
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install latexindent
        run: |
          sudo wget https://github.com/cmhughes/latexindent.pl/releases/download/V3.22.2/latexindent-linux -O /usr/bin/latexindent
          sudo chmod +x /usr/bin/latexindent
      - name: Run fomatter
        run: latexindent -w *.tex
      - uses: EndBug/add-and-commit@v9
        with:
          add: '*.tex'
          default_author: github_actions
          message: 'Autofmt by latexindent'
