permissions:
  contents: read
on:
  push:
    branches: [ master ]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    name: build thesis
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Accept License
        run: echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
      - name: Install font
        run: |
          sudo apt-get install ttf-mscorefonts-installer
          fc-cache -f
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: paper.tex
          extra_fonts: fonts/*
          latexmk_use_xelatex: true
